language: node_js
node_js:
  - '6.10'
  - '8.10'
  - '10.15'
matrix:
  allow_failures:
  - node_js: '6.10'
script:
  - npm run lint
  - npm test
  - npm run check-coverage
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
